### ISSUE TITLE
VOT test 

### ISSUE THREAD

**Issue by yangkang779** [got-10k/toolkit#11]
你好，我想请问一下用这个接口的VOT18的评测得到的结果，在baseline 的EAO为0.24+，可是实时的上面才0.20或者0.19，看了一下帧率，40多帧每秒，是实时的算法，结果应该差不太多啊，baseline和实时的EAO得分。谢谢。

**Comment by huanglianghua** [comment]
Hi @yangkang779, the toolkit only implements AO and A (accuracy), R (robustness) metrics for VOT challenges, and we haven't reproduced the EAO (expected average overlap) metric, which is far more complex (see issue [202](https://github.com/votchallenge/vot-toolkit/issues/202) in vot-toolkit).

Probably the 0.24+ you get from this toolkit is the A (accuracy) score instead of EAO. Thanks.

**Comment by huanglianghua** [comment]
Perhaps a better way would be to use the GOT-10k toolkit for generating the baseline/realtime tracking results on VOT, while still using the [vot-toolkit](https://github.com/votchallenge/vot-toolkit) for evaluation. The result files and path structure are compatible.

**Comment by huanglianghua** [comment]
Although your tracker runs at over 40 fps on average, on a few sparse frames it could still be slower than realtime, where a few frames could be skipped and would cause significant drops on accuracy and robustness. Can you check your result time files and find out the frames when your tracker runs below realtime? The performance drops were probably caused by those frames.
