### ISSUE TITLE
error 404 on evaluation server

### ISSUE THREAD

**Issue by happyjin** [got-10k/toolkit#2]
Hi:
Thanks for your awesome project. The server is not available right now. Can you please fix the server? And I want to compare my results with some other trackers. Could you please tell me how to plot curves for multiple trackers in the same panel like what you have done in the paper? Thanks in advance!

**Comment by happyjin** [comment]
Hi:
If I want to compare my model with other trackers on VOT or OTB dataset. Do you offer data for other trackers on OTB and VOT dataset?

**Comment by huanglianghua** [comment]
Hi, @happyjin, thanks for your interests. The links have been fixed in the new commit of this repo (master branch).

We provide GOT-10k tracking results/reports on the [download page](http://47.94.140.97/downloads) of GOT-10k website.

Currently we have no plan to gather and release OTB and VOT results. For VOT datasets, you can directly download results from its homepage, e.g., http://data.votchallenge.net/vot2018/vot2018_results.zip.

**Comment by happyjin** [comment]
Hi @huanglianghua , thanks for your swift fixing and the link which is really helpful!

**Comment by happyjin** [comment]
I have found @huanglianghua  `ExperimentOTB` is able to plot the OPE curve by `report()` function. However, `ExperimentVOT` is not able to plot it. Will you update this class in order to implement the plot function as well?

**Comment by huanglianghua** [comment]
@happyjin I had attempted to reproduce the EAO metric and EO curves of `VOT` experiments, but not successful, they are just too complex :< and the `region_overlap` used in official VOT toolkit produces slightly different results from standard IoU (see [here](https://github.com/votchallenge/vot-toolkit/issues/202)). We may try to reproduce precise evaluation code for VOT experiments later.

A faster way would be to run your tracker using `ExperimentVOT.run` method while evaluating the performance using [official VOT toolkit](https://github.com/votchallenge/vot-toolkit.git). The file structure of saved tracking results is consistent with that from official toolkit.
