### ISSUE TITLE
Can not get evaluation result after submitting to the server

### ISSUE THREAD

**Issue by StrangerZhang** [got-10k/toolkit#3]

**Comment by huanglianghua** [comment]
@StrangerZhang Thanks for the feedback, we'll check your submission. Could you tell us was the compressed .zip file generated using the toolkits or by yourself?

**Comment by StrangerZhang** [comment]
By myself, but I already check the format. My account name is "stranger", if I made some mistakes, let me know.

**Comment by huanglianghua** [comment]
@StrangerZhang We have checked your submission. The error was caused by the `cwd` when compressing files. By default, we compress all results under `<tracker_name>` folder but we found your results are compressed under the root path of `<tracker_name>`.

We have fixed this and your submission format should also work. You scores should be updated now.

**Comment by StrangerZhang** [comment]
Tks
